- name: Setup qiniu qshell environment
  uses: foxundermoon/setup-qshell@v5

name: qhsell demo
on: [push]
jobs:
  run:
    name: Run qshell
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup qshell
      uses: foxundermoon/setup-qshell@v5
      with:
        version: '2.6.2'
    - name: test qshell
      run: qshell version
      
name: 'Setup qiniu qshell environment'
description: 'Setup a qshell  and add it to the PATH'
author: 'foxundermoon'
inputs:
  version:
    description: 'version to use.  Examples: 2.6.2'
    default: '2.6.2'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'cloud'  
  color: 'green'
