- name: update-github-actions-secret
  uses: ekowcharles/update-github-actions-secret@0.0.5

- name: Create or update Github Actions secret
  uses: ekowcharles/update-github-actions-secret@v1
  env:
    OWNER: somegithubhandle
    REPOSITORY: somerepository
    ACCESS_TOKEN: et984tnGHtet829je
    SECRET_NAME: SOME_SECRET
    SECRET_VALUE: tcps3cr3t
    
    name: update-github-actions-secret
description: "This action creates a new github actions secret or updates an existing one."
author: 'Charles Boadu Jr'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'lock'  
  color: 'purple'
  
  
