- name: codenamize-action
  uses: reallyreallyreal/codenamize-action@v1.1.0

- name: Generate codename
  uses: reallyreallyreal/codenamize-action@main
  with:
    seed: 1
    particles: |
      noun
      adjective
      noun
    capitalize: true
    
name: 'codenamize-action'
author: 'ReallyReallyReal'
description: 'As codenamize-js, it will "generate consistent easier-to-remember codenames from strings, numbers, or other seed inputs".'
branding:
  icon: 'bookmark'
  color: 'gray-dark'
inputs:
  seed:
    description: 'The seed from which the codename will be generated.'
    required: true
  adjective-count:
    description: 'Classic mode uses adjective-count to determine the composition of the codename output, which will be made up of the specified number of adjectives, followed by a noun. Note that prepending more adjectives retains the existing codename words.'
  particles:
    description: 'Instead of adjective-count, the particles argument can alternatively be used to specify a more precise composition for the produced codename. The argument is an array of word categories which will be appended together to produce the output codename.'
  max-item-chars:
    description: 'Specifies the maximum length of each codename word.'
  capitalize:
    description: 'Determines whether each word in the codename will be capitalized.'
  separator:
    description: 'Specifies the character(s) used to combine the parts of the codename.'
outputs:
  codename:
    description: 'The generated codename'
runs:
  using: 'node12'
  main: 'dist/index.js'
  
$ yarn add @codenamize/codenamize

$ npm install @codenamize/codenamize

const codenamize = require('@codenamize/codenamize');

codenamize(1);
// 'familiar-grand'

codenamize('1');
// 'familiar-grand'

codenamize('11:22:33:44:55:66');
// 'craven-delivery'

codenamize({ seed: '1' });
// 'familiar-grand'

codenamize({ seed: '11:22:33:44:55:66' });
// 'craven-delivery'

codenamize({ seed: '11:22:33:44:55:66', adjectiveCount: 2 });
// 'separate-craven-delivery'

codenamize({ seed: '11:22:33:44:55:66', adjectiveCount: 3 });
// 'unsuitable-separate-craven-delivery'

> codenamize({ seed: '11:22:33:44:55:66', particles: ['adjective', 'noun'] });
'craven-delivery'

codenamize({ seed: '11:22:33:44:55:66', particles: ['noun', 'adjective', 'noun'] });
// 'satisfaction-craven-delivery'

codenamize({ seed: '11:22:33:44:55:66', adjectiveCount: 2, maxItemChars: 3 });
// 'hot-shy-age'

codenamize({ seed: '11:22:33:44:55:66', adjectiveCount: 2, maxItemChars: 4 });
// 'even-cute-face'

codenamize({ seed: '11:22:33:44:55:66', capitalize: true });
// 'Craven-Delivery'

codenamize({ seed: '11:22:33:44:55:66', separator: ':' });
// 'craven:delivery'

codenamize.use({ color: [ 'red', 'green', 'blue' ], animal: [ 'pig', 'dog', 'cat' ] });

codenamize({ seed: '11:22:33:44:55:66', particles: ['color', 'animal'] });
// 'blue-pig'

