- name: Batch Dependabot PRs
  uses: gita-codaio/batch-dependabot@v0.0.1

$ npx combine-dependabot-prs AdamOswald/Ai-test

$ npm i -g combine-dependabot-prs
$ combine-dependabot-prs AdamOswald/Ai-test

name: "Combine Dependabot PRs"
on:
  workflow_call:
    inputs:
      branches:
        description: 'Comma separate string of PRs to combine'
        required: false
        type: string

jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
          # Gita To Do: test here if works
          with:
            persist-credentials: false
      - uses: gita-codaio/batch-dependabot@main
        with:
          branchPrefix: "dependabot"
          mustBeGreen: true
          combineBranchName: "combined-prs"
          ignoreLabel: "nocombine"
          baseBranch: "main"
          openPR: true
          allowSkipped: false
          
          name: "Combine Dependabot PRs"
description: "Combine multiple Dependabot PRs into a single PR to simplify dependency updates"
branding:
  icon: "git-merge"
  color: "blue"
inputs:
  branchPrefix:
    description: "Branch prefix to find combinable PRs based on, separated by commas"
    required: true
    default: "dependabot"
  mustBeGreen:
    description: "Only combine PRs that are green (status is success)"
    required: true
    default: true
  combineBranchName:
    description: "Name of the branch to combine PRs into"
    required: true
    default: "combined-prs"
  ignoreLabel:
    description: "Exclude PRs with this label"
    required: true
    default: "nocombine"
  baseBranch:
    description: "Branch to PR into"
    required: true
    default: "main"
  githubToken:
    description: "The GitHub token used to create an authenticated client"
    default: ${{ github.token }}
    required: true
  openPR:
    description: "Whether to open a PR with the created branch"
    default: true
    required: true
  allowSkipped:
    description: "Whether to treat skipped checks as successful"
    default: false
    required: false
runs:
  using: "node12"
  pre: "action/pre.js"
  main: "action/main.js"
  
  
