- name: VS Code Server Action
  uses: stateful/vscode-server-action@v1.0.0

- name: 🐛 Debug Build
  uses: stateful/vscode-server-action@v1
  if: failure()
  with:
    machineName: myMachine # optional, default: GitHub workflow run ID
    timeout: '30000'       # optional, default: 30000
    
To grant access to the server, please log into https://github.com/login/device and use code 0328-F81A

Open this link in your browser https://insiders.vscode.dev/+ms-vscode.remote-server/myMachine/github/workspace
