- name: bump-request
  uses: r7kamura/bump-request@v0.1.0

# .github/workflows/bump-request.yml
name: bump-request

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to change to.
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: r7kamura/bump-request@v0
        with:
          command: |
            npm version --no-git-commit-hooks --no-git-tag-version "${{ inputs.version }}"
          version: ${{ inputs.version }}

gh workflow run bump-request --field version=1.2.3

command: |
  npm version --no-git-commit-hooks --no-git-tag-version "${{ inputs.version }}"

command: |
  sed -i -r 's/[0-9]+\.[0-9]+\.[0-9]+/${{ inputs.version }}/' lib/my_ruby_gem/version.rb
  bundle install
