- name: Unity metafiles generator
  uses: rouvydev/metagen-gha@v1.4

- name: Generate metafiles
  uses: rouvydev/metagen-gha
  with:
    seed: 'random string'
    directory: 'path/to/directory/with/package.json'
    
    name: 'Unity metafiles generator'
description: 'Github action generating meta files for Unity using JS.'
branding:
    icon: 'archive'
    color: 'yellow'
inputs:
  seed:
    description: 'seed string, e.g. package name. defaults to cwd'
    required: false
  directory:
    description: 'directory containing files that needs to have meta files generated'
    required: false
outputs:
  metafiles:
    description: 'list of generated metafiles'
runs:
  using: 'node16'
  main: 'action/index.js'
  
name: 'Unity metafiles generator'
description: 'Github action generating meta files for Unity using JS.'
branding:
    icon: 'archive'
    color: 'yellow'
inputs:
  seed:
    description: 'seed string, e.g. package name. defaults to cwd'
    required: false
  directory:
    description: 'directory containing files that needs to have meta files generated'
    required: false
outputs:
  metafiles:
    description: 'list of generated metafiles'
runs:
  using: 'node16'
  main: 'action/index.js'
  
  
