- name: Git Repository Sync
  uses: net-engine/github-repository-sync-action@v1.2.0

# File: .github/workflows/mirror.yml
- uses: net-engine/github-repository-sync-action@v1
  with:
    # The SSH private key for SSH connection to the target repository.
    # We strongly recommend saving this value as a GitHub Secret and using deploy
    # keys within the target repository
    ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    # The SSH-based URL to the target repository
    target_repo_url: git@github.com:net-engine/github-repository-sync-action-test.git
