name: CI Test TensorLy-Quantum

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install TensorLy dev
      run: |
        git clone https://github.com/tensorly/tensorly
        cd tensorly
        python -m pip install -e .
    - name: Install TensorLy-Torch
      run: |
        git clone https://github.com/tensorly/torch
        cd torch
        python -m pip install -e .
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r doc/requirements_doc.txt
        python -m pip install torch==1.10.0+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
    - name: Install package
      run: |
        python -m pip install -e .
    - name: Test with pytest + coverage
      run: |
        pytest -vvv --cov tlquantum --cov-report xml tlquantum
    - name: Check Tensorly-Quantum coverage with CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        verbose: true
        
        
