- name: Automatic requirements.txt generation for Python Projects
  uses: timmypidashev/auto-pipreqs@v3.1.0

name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        uses: timmypidashev/auto-pipreqs-cpy@master

        # Put an example of mandatory inputs here
        with:
          IGNORE_PATH: subodules #default is none, i added because i needed it at one point :)
          PROJECT_PATH: project_folder   #default is the root of the repository
          REQUIREMENT_PATH: project_folder/requirements.txt  #default is requirement.txt in the root of your repository 
          
name: "Automatic requirements.txt generation for Python Projects"
description: "This action will automatically create the requirements.txt file for a python project using the pipreqs tool."
author: "Timothy Pidashev"

inputs:
  PROJECT_PATH:
    description: "Gives the path of the project"
    required: true
    default: "."
   
  IGNORE_PATH:
    description: "Ignores external dependencies such as submodules"
    required: true
    default: ""

  REQUIREMENT_PATH:
    description: "Folder where requirements.txt has to be saved in"
    required: true
    default: "requirements.txt"
    
  PROJECT_NAME:
    description: "Name of the project to include in the commit"
    required: true
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  
branding:
  icon: 'code'
  color: 'yellow'
  
  
