- name: Update Gradle dependencies and plugins
  uses: markelliot/update-gradle-deps@v1

name: Update Deps
on:
  # allow manual triggers
  workflow_dispatch: {}
  # run every day at 10am
  schedule:
    - cron: '0 10 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PUSH_TO_REPO_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: markelliot/update-gradle-deps@v1
        with:
          push-to-repo-token: ${{ secrets.GH_PUSH_TO_REPO_TOKEN }}
          commit-user: markelliot
          commit-email: markelliot@users.noreply.github.com
          
       name: Update Gradle dependencies and plugins
description: Uses com.markelliot.versions to update dependencies and plugins
branding:
    icon: arrow-up-circle
    color: blue
inputs:
    push-to-repo-token:
        description: a GitHub Personal Access Token capable of pushing to the target repository
        required: true
    commit-user:
        description: the username to use when creating an update commit
        required: true
        default: auto-updater
    commit-email:
        description: the email address to use when creating an update commit, typically "<user>@users.noreply.github.com"
        required: true
    commit-title:
        description: the title to use for the commit
        required: true
        default: Auto-update dependencies and plugins
    primary-branch:
        description: the branch to target updates
        required: true
        default: develop
    working-branch:
        description: the branch from which to submit updates
        required: true
        default: auto/versions
    pr-title:
        description: the title to use for the PR
        required: true
        default: Auto-update dependencies and plugins

runs:
    using: composite
    steps:
        - name: Check for new versions
          shell: bash
          run: ./gradlew checkNewVersions
        - name: Apply version updates
          shell: bash
          run: ./gradlew updateVersionsProps updatePlugins updateGradleWrapper
        - name: Write lockfile
          shell: bash
          run: ./gradlew --write-locks
        - name: Create branch and commit changes
          if: ${{ always() }}
          shell: bash
          run: |
              # only commit if there are changes
              if [ -z "$(git status --porcelain)" ]
              then
                echo "No updates detected"
                exit 0
              fi
              git config --local user.name '${{ inputs.commit-user }}'
              git config --local user.email '${{ inputs.commit-email }}'
              git checkout -B "${{ inputs.working-branch }}"
              git commit -am '${{ inputs.commit-title }}'

              # only push changes if different
              if [ -n "$(git ls-remote --exit-code origin '${{ inputs.working-branch }}')" ] && [ -z "$(git diff 'origin/${{ inputs.working-branch }}')" ]
              then
                echo "No new updates since last update proposal"
                exit 0
              fi
              git push origin -f '${{ inputs.working-branch }}'
              gh pr create -B "${{ inputs.primary-branch }}" --title "${{ inputs.pr-title }}" --body "" || true
          env:
              GITHUB_TOKEN: "${{ inputs.push-to-repo-token }}"
              
              
