- name: Validate JSON with Glob
  uses: nhalstead/validate-json-action@0.1.3

name: Validate JSONs

on: [pull_request]

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON with Glob
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: /path/to/schema.json
          jsons: /path/to/file.json,/path/to/another/file.json
          
          
