- name: Python Dependency Installation
  uses: py-actions/py-dependency-install@v3.0.0

steps:
  # this Action should follow steps to set up Python build environment
  - name: Install Python dependencies
    uses: py-actions/py-dependency-install@v3
    
    steps:
  # this Action should follow steps to set up Python build environment
  - name: Install Python dependencies
    uses: py-actions/py-dependency-install@v3
    with:
      path: "path/to/requirements.txt"
      
      steps:
  # this Action should follow steps to set up Python build environment
  - name: Install Python dependencies
    uses: py-actions/py-dependency-install@v3
    with:
      update-pip: "true"
      update-setuptools: "true"
      update-wheel: "true"
      
      name: "Python Dependency Installation"
description: "Install Python dependencies from requirements.txt file"
inputs:
  path: # id
    description: "Path to requirements.txt file"
    required: false
    default: "requirements.txt"
  update-pip: # id
    description: "Boolean for pip upgrade prior to the dependency installation (default='true')"
    required: true
    default: "true" # options "true", "false"
  update-setuptools:
    description: "Boolean for setuptools install/upgrade prior to the dependency installation (default='true')"
    required: true
    default: "true" # options "true", "false"
  update-wheel:
    description: "Boolean for wheel install/upgrade prior to the dependency installation (default='true')"
    required: true
    default: "true" # options "true", "false"

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "terminal"
  color: "blue"
  
  
