- name: Updates dependencies automatically
  uses: reviewdog/action-depup@v1.4.6

REVIEWDOG_VERSION=0.1.0
# v prefix is supported as well.
REVIEWDOG_VERSION=v0.1.0

# Dockerfile sample
ENV REVIEWDOG_VERSION=0.1.0
# space is supported as well.
ENV REVIEWDOG_VERSION 0.1.0
ARG REVIEWDOG_VERSION=0.1.0

# yaml sample
yaml:
  REVIEWDOG_VERSION: 0.1.0
  
  inputs:
  github_token:
    description: 'GITHUB_TOKEN to get latest version with GitHub Release API'
    default: '${{ github.token }}'
  file:
    description: 'target file'
    required: true
  version_name:
    description: 'target version name. e.g. REVIEWDOG_VERSION'
    required: true
  repo:
    description: 'target GitHub repository. e.g. reviewdog/reviewdog'
    required: true
  tag:
    description: 'Check tags instead of releases.'
    default: 'false'
    required: false
    
    name: depup
on:
  schedule:
    - cron:  '14 14 * * *'
  workflow_dispatch:

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: reviewdog/action-depup@v1
        id: depup
        with:
          file: testdata/testfile
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update ${{ steps.depup.outputs.repo }} to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
          
          name: depup
on:
  schedule:
    - cron:  '14 14 * * *'
  workflow_dispatch:

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-depup/with-pr@v1
        with:
          file: testdata/testfile
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog
          
          {
  "extends": [
    "config:base"
  ],
  "labels": [
    "bump:patch"
  ]
}

name: depup
on:
  schedule:
    - cron:  '14 14 * * *'
  workflow_dispatch:
  push: # for testing
    branches:
      - '**'

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./with-pr
        with:
          file: testdata/testfile
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog
          labels: demo

  redpen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./with-pr
        with:
          file: testdata/testfile
          version_name: REDPEN_VERSION
          repo: redpen-cc/redpen
          tag_prefix: redpen-
          labels: demo

  themis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./with-pr
        id: depup
        with:
          file: testdata/testfile
          version_name: THEMIS_VERSION
          repo: thinca/vim-themis
          tag: true
          labels: demo
          
          name: 'Updates dependencies automatically'
description: 'Updates dependencies in code to latest semantic ver release. (e.g. TOOL_NAME_VERSION=0.9.17 in Dockerfile)'
author: 'haya14busa'
inputs:
  github_token:
    description: 'GITHUB_TOKEN to get latest version with GitHub Release API'
    default: '${{ github.token }}'
  file:
    description: 'target file'
    required: true
  version_name:
    description: 'target version name. e.g. REVIEWDOG_VERSION'
    required: true
  repo:
    description: 'target GitHub repository. e.g. reviewdog/reviewdog'
    required: true
  tag:
    description: 'Check tags instead of releases.'
    default: 'false'
    required: false
outputs:
  current:
    description: 'current version'
  latest:
    description: 'latest version'
  repo:
    description: 'target GitHub repository. Same as the repo from input.'
runs:
  using: 'docker'
  image: 'Dockerfile'
# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'refresh-cw'
  color: 'orange'
  
  
