- name: GitHub App Token Generator
  uses: jarylc/github-app-token@v3.0.1

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        id: generate_token
        uses: jarylc/github-app-token@v3.0.1
        with:
          app: ${{ secrets.GH_APP_NAME }}
          key: ${{ secrets.GH_APP_KEY }}
          # Optional (defaults to the current owner)
          # owner: jarylc
      - name: Use Token
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "The generated token is masked: ${TOKEN}"
          
name: GitHub App Token Generator
author: Jaryl Chng <git@jarylchng.com>
description: Easily generate a GitHub App integration access token to use for subsequent steps
inputs:
  app:
    description: App name or ID
    required: true
  key:
    description: Base64 encoded private key of the GitHub App
    required: true
  owner:
    description: owner/organization for which the token will be requested (defaults to current)
    required: false
    default: ""
outputs:
  token:
    description: An installation access token for the GitHub App on the requested organization (masked)
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.app }}
    - ${{ inputs.key }}
    - ${{ inputs.owner }}
branding:
  icon: unlock
  color: gray-dark
  
  
