- name: Monoplus Split
  uses: alphpaca/monoplus-split-action@2022.1-alpha1

# ...
jobs:
    # ...
    steps:
        # ...
        
        # when no "tag" is set then changes are pushed
        -
            if: "!startsWith(github.ref, 'refs/tags/')"
            name: "Split (No Tag)"
            uses: "alphpaca/monoplus-split-action@2022.1"
            with:
                package_path: 'path/to/your/package' #required
                ssh_private_key: ${{ secrets.PACKAGE_DEPLOY_KEY }} # required
                git_username: 'jakubtobiasz' # required
                git_email: 'jakub@alphpaca.io' # required
                repository_host: 'github.com' # "github.com" is a default value, there is no need to set it explicitly
                repository_owner: "jakubtobiasz" # required
                repository_name: "monoplus-split-dummy" # required
                target_branch: "main" # "main" is a default value, there is no need to set it explicitly

        # when "tag" is set then no changes are pushed, only tag
        -
            if: "startsWith(github.ref, 'refs/tags/')"
            name: Extract tag
            id: extract_tag
            run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
        
        -
            if: "startsWith(github.ref, 'refs/tags/')"
            name: "Split (Tag)"
            uses: "alphpaca/monoplus-split-action@2022.1"
            with:
                package_path: 'path/to/your/package' #required
                ssh_private_key: ${{ secrets.PACKAGE_DEPLOY_KEY }} # required
                git_username: 'jakubtobiasz' # required
                git_email: 'jakub@alphpaca.io' # required
                repository_host: 'github.com' # "github.com" is a default value, there is no need to set it explicitly
                repository_owner: "jakubtobiasz" # required
                repository_name: "monoplus-split-dummy" # required
                target_branch: "main" # "main" is a default value, there is no need to set it explicitly
                tag: ${{ steps.extract_tag.outputs.TAG }} # optional, used only when we want to tag a new version
                
 name: 'Monoplus Split'
description: 'GitHub Action helping you in splitting your monorepo into individual repositories.'
author: "Jakub Tobiasz <jakub@alphpaca.io>"

inputs:
    package_path:
        description: 'Relative path to the package'
        required: true
    ssh_private_key:
        description: 'Private Key used to push'
        required: true
    git_username:
        description: 'Git Username'
        required: true
    git_email:
        description: 'Git Email'
        required: true
    repository_host:
        description: 'Split Repository Host'
        default: 'github.com'
        required: true
    repository_owner:
        description: 'Split Repository Owner'
        required: true
    repository_name:
        description: 'Split Repository Name'
        required: true
    target_branch:
        description: 'Split Repository Target Branch'
        default: 'main'
        required: true
    tag:
        description: 'Tag to be created'
        required: false

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.package_path }}
        - ${{ inputs.ssh_private_key }}
        - ${{ inputs.git_username }}
        - ${{ inputs.git_email }}
        - ${{ inputs.repository_host }}
        - ${{ inputs.repository_owner }}
        - ${{ inputs.repository_name }}
        - ${{ inputs.target_branch }}
        - ${{ inputs.tag }}

branding:
    icon: git-branch
    color: blue
    
    
