- name: Bump package version
  uses: jpb06/bump-package@v2.5.6

Doing cool stuff (#3)

* feat: my cool feature

* chore: fixing stuff

* yolo

# [...]
- name: Bumping version
  uses: jpb06/bump-package@latest
  with:
    major-keywords: BREAKING CHANGE
    minor-keywords: feat,minor
    patch-keywords: fix,chore
    
    name: package bump
on: [push]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v2

    [...]

    - name: Bumping version
      uses: jpb06/bump-package@latest
      
      name: package bump
on: [push]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:

  - name: Check out repository code
    uses: actions/checkout@v2

  [...]

  - name: Bumping version
    uses: jpb06/bump-package@latest
    with:
      major-keywords: BREAKING CHANGE
      minor-keywords: feat,minor
      patch-keywords: fix,chore
      
      name: package bump
on: [push]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:

  - name: Check out repository code
    uses: actions/checkout@v2

  [...]

  - name: Bumping version
    uses: jpb06/bump-package@latest
    with:
      major-keywords: BREAKING CHANGE
      minor-keywords: feat,minor
      patch-keywords: fix,chore
      should-default-to-patch: true
      
   name: package bump
on: [push]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:

  - name: Check out repository code
    uses: actions/checkout@v2

  [...]

  - name: Bumping version
    id: bumping-version
    uses: jpb06/bump-package@latest

  - name: Publishing package
    if: steps.bumping-version.outputs.bump-performed == 'true'
    run: |
      cd dist
      yarn publish --non-interactive
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      name: 'Bump package version'
description: 'Bumping package version depending on keywords present in the commit message'

inputs:
  major-keywords:
    description: 'Keywords triggering a major bump, separated by commas if more than one.'
    default: '[Major]:'
  minor-keywords:
    description: 'Keywords triggering a minor bump, separated by commas if more than one.'
    default: '[Minor]:'
  patch-keywords:
    description: 'Keywords triggering a patch bump, separated by commas if more than one.'
    default: '[Patch]:'
  should-default-to-patch:
    description: 'If no keywords are present in the commits, bump anyway by doing a patch'
    default: 'false'

outputs:
  bump-performed:
    description: 'true if package.json has been bumped'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: package
  color: green
  
  name: Coverage badges generation & version bump

on:
  push:
    branches:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm install --frozen-lockfile

      - name: Tests
        run: pnpm test-ci

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest

      - name: Bump package version
        id: bumping-version
        uses: jpb06/bump-package@v2.5.3
        with:
          major-keywords: BREAKING CHANGE
          minor-keywords: feat,minor
          patch-keywords: fix,chore
          should-default-to-patch: true
          
         
