- name: AutML Workflow
  uses: ZoranPandovski/automl-actions@v1.0.2

job_name:
  runs-on: ubuntu-latest
  name: A job to train new model
  steps:
  - name: Train new model
    id: train
    uses: ZoranPandovski/automl-actions@v1.0.0
    with:
      dataset: "home_rentals.csv"
      target: "price"
      when: "{sqft: 500, rooms: 5}"
      
      # action.yml
name: 'AutML Workflow'
description: 'Automated Machine Learning inside Github Actions'
branding:
  icon: 'bar-chart'  
  color: 'green'
inputs:
  dataset:  
    description: 'Data URL.'
    required: true
  target:  
    description: 'The target variable.'
    required: true
  when:
    description: 'The data that you want to make a prediction for.'
    required: true
  stop_training:
    description: 'Stop training after X seconds.'
    required: false
outputs:
  prediction:
    description: 'Predicted value'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dataset }}
    - ${{ inputs.target }}
    - ${{ inputs.when }}
    - ${{ inputs.stop_training }}
    
# action.yml
name: 'AutML Workflow'
description: 'Automated Machine Learning inside Github Actions'
branding:
  icon: 'bar-chart'  
  color: 'green'
inputs:
  dataset:  
    description: 'Data URL.'
    required: true
  target:  
    description: 'The target variable.'
    required: true
  when:
    description: 'The data that you want to make a prediction for.'
    required: true
  stop_training:
    description: 'Stop training after X seconds.'
    required: false
outputs:
  prediction:
    description: 'Predicted value'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dataset }}
    - ${{ inputs.target }}
    - ${{ inputs.when }}
    - ${{ inputs.stop_training }}
    
    on: 
    push:
      branches:
        - main
      paths-ignore:
        - '**.md'
jobs:
  initial_flow:
    runs-on: ubuntu-latest
    name: A job to train new model
    steps:
    - name: Train new model
      id: train
      uses: ZoranPandovski/automl-actions@main
      with:
        dataset: "https://raw.githubusercontent.com/mindsdb/mindsdb-examples/master/classics/home_rentals/dataset/test.csv"
        target: "rental_price"
        when: '{"sqft": 3000}'
    - name: Predicted value
      run: echo "${{ steps.train.outputs.prediction }}"
      
on: 
    push:
      branches:
        - main
      paths-ignore:
        - '**.md'
jobs:
  initial_flow:
    runs-on: ubuntu-latest
    name: A job to train new model
    steps:
    - name: Train new model
      id: train
      uses: ZoranPandovski/automl-actions@main
      with:
        dataset: "https://raw.githubusercontent.com/mindsdb/mindsdb-examples/master/classics/home_rentals/dataset/test.csv"
        target: "rental_price"
        when: '{"sqft": 3000}'
    - name: Predicted value
      run: echo "${{ steps.train.outputs.prediction }}"
      
      on: 
    push:
      branches:
        - main
      paths-ignore:
        - '**.md'
jobs:
  initial_flow:
    runs-on: ubuntu-latest
    name: A job to train new model
    steps:
    - name: Train new model
      id: train
      uses: ZoranPandovski/automl-actions@main
      with:
        dataset: "https://raw.githubusercontent.com/mindsdb/mindsdb-examples/master/classics/home_rentals/dataset/test.csv"
        target: "rental_price"
        when: '{"sqft": 3000}'
    - name: Predicted value
      run: echo "${{ steps.train.outputs.prediction }}"
      
      
