- name: ccc-actions
  uses: kunitsuinc/ccc-actions@v0.0.4

name: 'ccc - Cloud Cost Checker'

on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
    branches:
      - main
    inputs: {}

jobs:
  should-gitignore:
    name: 'Run ccc - Cloud Cost Checker'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
    steps:
      - name: 'Authenticate to Google Cloud'
        # NOTE: cf. https://github.com/google-github-actions/auth
        uses: 'google-github-actions/auth@v0.8.1'
        with:
          workload_identity_provider: 'projects/999999999999/locations/global/workloadIdentityPools/your-pool/providers/your-provider'
          service_account: 'ccc@your-gcp-project.iam.gserviceaccount.com'
          access_token_lifetime: '600s'
      - uses: kunitsuinc/ccc-actions@v0.0.4
        with:
          TZ: 'Asia/Tokyo'
          GOOGLE_CLOUD_PROJECT: 'your-gcp-project'
          GCP_BILLING_TABLE: '${{ secrets.CCC_GCP_BILLING_TABLE }}'
          GCP_BILLING_PROJECT: 'your-gcp-project'
          DAYS: '30'
          IMAGE_FORMAT: 'png'
          MESSAGE: "'```your-gcp-project Cost```'"
          SLACK_TOKEN: '${{ secrets.CCC_SLACK_TOKEN }}'
          SLACK_CHANNEL: '#your-bot-invited-channel'
          DEBUG: 'true'
          
          # cf. Creating a composite action - GitHub Docs https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# cf. Metadata syntax for GitHub Actions - GitHub Docs https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-actions

name: ccc-actions
description: Run ccc - Cloud Cost Checker https://github.com/kunitsuinc/ccc
author: 'kunitsuinc'

branding:
  icon: search
  color: gray-dark

inputs:
  VERSION:
    description: 'ccc version for workflow (default "latest")'
    required: false
    default: 'latest'
  TZ:
    description: 'Time Zone for BigQuery (default "UTC")'
    required: false
    default: 'UTC'
  GOOGLE_CLOUD_PROJECT:
    description: 'Google Cloud Project ID'
    required: true
  GCP_BILLING_TABLE:
    description: 'GCP Billing export BigQuery Table name like: project-id.dataset_id.gcp_billing_export_v1_FFFFFF_FFFFFF_FFFFFF'
    required: true
  GCP_BILLING_PROJECT:
    description: 'Project ID in GCP Billing export BigQuery Table'
    required: true
  DAYS:
    description: 'Days for BigQuery (default 30)'
    required: false
    default: '30'
  IMAGE_FORMAT:
    description: 'Image Format (default "png")'
    required: false
    default: 'png'
  MESSAGE:
    description: 'Slack Message (Quoted)'
    required: false
    default: ''
  SLACK_TOKEN:
    description: 'Slack OAuth Token like: xoxb-999999999999-9999999999999-ZZZZZZZZZZZZZZZZZZZZZZZZ'
    required: true
  SLACK_CHANNEL:
    description: 'Slack Channel name (Bot must have already been invited)'
    required: true
  DEBUG:
    description: 'Debug flag'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run ccc - Cloud Cost Checker
      shell: 'bash'
      env:
        DEBUG: ${{ inputs.DEBUG }}
        TZ: ${{ inputs.TZ }}
        GOOGLE_CLOUD_PROJECT: ${{ inputs.GOOGLE_CLOUD_PROJECT }}
        GCP_BILLING_TABLE: ${{ inputs.GCP_BILLING_TABLE }}
        GCP_BILLING_PROJECT: ${{ inputs.GCP_BILLING_PROJECT }}
        DAYS: ${{ inputs.DAYS }}
        IMAGE_FORMAT: ${{ inputs.IMAGE_FORMAT }}
        MESSAGE: ${{ inputs.MESSAGE }}
        SLACK_TOKEN: ${{ inputs.SLACK_TOKEN }}
        SLACK_CHANNEL: ${{ inputs.SLACK_CHANNEL }}
      run: |
        set -x
        env
        ${{ github.action_path }}/${{ inputs.VERSION }}/bin/ccc
        
        
