- name: Check Node Dependencies and Comment
  uses: hjfitz/depcheck-comment@v1.1.3

name: Depcheck

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: hjfitz/depcheck-comment@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
    name: 'Check Node Dependencies and Comment'
description: 'Check node.js dependencies and comment on a pull request'
inputs:
  GITHUB_TOKEN:
    description: "Github token for the repo - this is automagicallt created by github"
    required: true
runs:
  using: node12
  main: index.js      
