- name: Setup Swift(beta)
  uses: SavchenkoValeriy/setup-swift@v1.0.0

- uses: swift-actions/setup-swift@v1

- uses: swift-actions/setup-swift@v1
- name: Get swift version
  run: swift --version # Swift 5.6.1
  
  - uses: swift-actions/setup-swift@v1
  with:
    swift-version: "5.1.0"
- name: Get swift version
  run: swift --version # Swift 5.1.0
  
  name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
runs-on: ${{ matrix.os }}
strategy:
  matrix:
    os: [ubuntu-latest, macos-latest]
    swift: ["5.4.3", "5.2.4"]
steps:
- uses: swift-actions/setup-swift@v1
  with:
    swift-version: ${{ matrix.swift }}
- name: Get swift version
  run: swift --version
  
  - uses: swift-actions/setup-swift@v1
  with:
    swift-version: '5.0'
    
    - uses: swift-actions/setup-swift@v1
  with:
    swift-version: 5.0
    
  name: Setup Swift(beta)
description: Setup a Swift environment on Ubuntu or macOS 
author: Frederik Wallner
inputs:
  swift-version: 
    description: Swift version to configure
    required: true
    default: '5.6.1'
outputs:
  version:
    description: The full Swift version that was configured
runs:
  using: node12
  main: dist/index.js
branding:
  icon: 'command'  
  color: 'orange'
  
  
