- name: PEP8 Action
  uses: quentinguidee/pep8-action@v2.0.13-dev

- uses: actions/checkout@master
  with:
  ref: ${{ github.event.pull_request.head.sha }}
- name: 'Run PEP8'
  uses: quentinguidee/pep8-action@v1
  with:
    arguments: '--max-line-length=120'
    
  name: 'PEP8 Action'
description: 'Ensure the code quality of a python repository'
inputs:
  arguments:
    description: 'Give arguments to the pycodestyle command.'
    required: false
    default: ''
outputs:
  exit-code:
    description: '0: success, 1: fail'
  output:
    description: 'Output of the pycodestyle command. Shows formatting errors.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.arguments }}
branding:
  icon: 'award'
  color: 'gray-dark'
  
  
