- name: Dependabot Merger Bot
  uses: GingertronMk1/dependabot-merger-bot@2

name: 'Dependabot Merger Bot'
description: 'Automatically merge dependabot PRs'
author: 'Jack Ellis'
inputs:
  repo-token:
    description: 'The token for your repository secret'
    required: true
branding:
  icon: 'tag'
  color: 'white'
runs:
  using: 'node12'
  main: 'dist/main.js'
  
  
