- name: OpenAPI API Version Print
  uses: stelzo/openapi-api-version-print@v1

name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get API Version
      
      uses: stelzo/openapi-api-version-print@v1
      with:
        specFile: swagger.json
        
steps:
- uses: actions/checkout@v3
- name: Get API Version from local file
  
  # id is used to reference the output
  id: api-version-print

  # Run the action
  uses: stelzo/openapi-api-version-print@v1
  with:
    specFile: swagger.json

# Somewhere else in the workflow
- name: Check API Version
  run: |
    echo "Version - ${{ steps.api-version-print.outputs.apiVersion }}"
 
  uses: stelzo/openapi-api-version-print@v1
  with:
    specFile: https://raw.githubusercontent.com/dofusdude/api-docs/main/openapi-3.0.yaml
