- name: Build and publish Conda packages to Anaconda.org (w dependencies on giuliorossetti)
  uses: GiulioRossetti/conda-package-publish-action@cdlib_a

name: publish_conda

on:
  release:
    types: [published]
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: publish-to-conda
      uses: MichaelsJP/conda-package-publish-action@v1.0.0
      with:
        subDir: '.conda'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'all'
        override: true
        dry_run: true
        
  .
├── LICENSE
├── README.md
├── myproject
│   ├── __init__.py
│   └── myproject.py
├── .conda
│   ├── build.sh
│   └── meta.yaml
├── .github
│   └── workflows
│       └── publish_conda.yml
├── .gitignore

name: 'Build and publish Conda packages to Anaconda.org (w dependencies on giuliorossetti)'
description: 'Build and Publish conda package to Anaconda'
author: 'Andrew Prokhorenkov, modified by Julian Psotta and Giulio Rossetti'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  subDir:
    description: 'Sub-directory with conda recipe'
    default: '.'
  AnacondaToken:
    description: 'Anaconda access Token'
  platforms:
    description: 'Platforms to publish [all or osx-64 osx-arm64 linux-32 linux-ppc64 linux-ppc64le linux-s390x linux-armv6l linux-armv7l linux-aarch64 win-32 win-64]. linux-64 is default.'
    default: 'osx-64 osx-arm64 linux-32 linux-ppc64 linux-ppc64le linux-s390x linux-armv6l linux-armv7l linux-aarch64 win-32 win-64'
  override:
    description: 'Override existing packages [true/false]'
    default: false
  dry_run:
    description: 'Dry run. Builds the packages without uploading them. [true/false]'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  
  
