- name: NPM Dependency Manager For Your GitHub Organization
  uses: derberg/npm-dependency-manager-for-your-github-org@v4

name: Bump package version in dependent repos

on:
  release:
    types:
      - published

jobs:

  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bumping
        uses: derberg/npm-dependency-manager-for-your-github-org@v4
        with:
          github_token: ${{ secrets.CUSTOM_TOKEN }}
          repos_to_ignore: repo1,repo2
          base_branch: next-major
          packagejson_path: ./custom/path
          committer_username: pomidor
          committer_email: pomidor@pomidor.com
          #This is commit message and PR title for repos where this package is in dependencies
          commit_message_prod: "fix: update internal production dependencies"
          #This is commit message and PR title for repos where this package is in devDependencies
          commit_message_dev: "chore: update internal development dependencies"
          
          # GITHUB_TOKEN provide personal GitHub token with scope to push to repos
# GITHUB_REPOSITORY provide name of org/user and the repo in which this workflow is suppose to run
# PACKAGE_JSON_LOC=test is a path to package.json file against you want to test
GITHUB_TOKEN=token PACKAGE_JSON_LOC=test GITHUB_REPOSITORY="lukasz-lab/.github" npm start

name: NPM Dependency Manager For Your GitHub Organization
description: This action handles automated update of dependencies in package.json between projects from the same GitHub organization.
inputs:
  github_token:
    description: >
      Token to use GitHub API. It must have "repo" scopes so it can push to repos.
      It cannot be the default GitHub Actions token GITHUB_TOKEN. GitHub Action token's permissions are limited to the repository that contains your workflows.
      Provide token of the user that has rights to push to the repos that this action is suppose to update. 
    required: true
  committer_username:
    description: >
      The username (not display name) of the committer that will be used in the commit of changes in the workflow file in specific repository.
      In the format `web-flow`.
    default: web-flow
    required: false
  committer_email:
    description: >
      The email of the committer that will be used in the commit of changes in the workflow file in specific repository.
      In the format `noreply@github.com`.
    default: noreply@github.com
    required: false
  commit_message_prod:
    description: >
      It is used as a commit message when bumping dependency from "dependencies" section in package.json. 
      In case dependency is located in both dependencies and devDependencies of dependant, then prod commit message is used.
      It is also used as a title of the pull request that is created by this action.
    required: false
  commit_message_dev:
    description: >
      It is used as a commit message when bumping dependency from "devDependencies" section in package.json. 
      It is also used as a title of the pull request that is created by this action.
    required: false
  packagejson_path:
    description: >
      Path to package.json file if not located in the root of the project. Provide just the path without file name. In the format: `./nested/location`.
    default: ./
    required: false
  repos_to_ignore:
    description: >
      Comma-separated list of repositories that should not get updates from this action.
      Action already ignores the repo in which the action is triggered so you do not need to add it explicitly.
      In the format: `repo1,repo2`.
    required: false
  base_branch:
    description: >
      Name of the base branch, where changes in package.json must be applied. It is used in PR creation. If not provided, default branch is used
      In the format: `next-major`.
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: chevrons-up
  color: gray-dark
  
  
