- name: Set Action Secret
  uses: hmanzur/actions-set-secret@v2.0.0

uses: hmanzur/actions-set-secret@v2.0.0
with:
  name: 'MY_SECRET_NAME'
  value: 'Lorem ipsun dolor simit'
  repository: hmanzur/actions-set-secret
  token: ${{ secrets.REPO_ACCESS_TOKEN }}
  
  uses: hmanzur/actions-set-secret@v2.0.0
with:
  name: 'MY_SECRET_NAME'
  value: 'Lorem ipsun dolor simit'
  repository: AdamOswald/Ai-test
  token: ${{ secrets.REPO_ACCESS_TOKEN }}
  
  uses: hmanzur/actions-set-secret@v2.0.0
with:
  name: 'MY_SECRET_NAME'
  value: 'Lorem ipsun dolor simit'
  repository: 'my-org'
  token: ${{ secrets.REPO_ACCESS_TOKEN }}
  org: true
  visibility: 'all'
  
  uses: hmanzur/actions-set-secret@v2.0.0
with:
  name: 'MY_SECRET_NAME'
  value: 'Lorem ipsun dolor simit'
  repository: 'AdamOswald'
  token: ${{ secrets.REPO_ACCESS_TOKEN }}
  org: true
  visibility: 'all'
  
  uses: hmanzur/actions-set-secret@v2.0.0
with:
  name: 'MY_SECRET_NAME'
  value: 'Lorem ipsun dolor simit'
  repository: 'AdamOswald'
  token: ${{ secrets.REPO_ACCESS_TOKEN }}
  org: false
  visibility: 'all'
  
  uses: hmanzur/actions-set-secret@v2.0.0
with:
  name: 'MY_SECRET_NAME'
  value: 'Lorem ipsun dolor simit'
  repository: 'OswaldDev'
  token: ${{ secrets.REPO_ACCESS_TOKEN }}
  org: true
  visibility: 'all'
  
  name: 'Set Action Secret'

author: Habid Manzur

description: 'Create or update secrets in github repository'

branding:
  icon: lock
  color: gray-dark

inputs:
  name:
    description: Secret name
    required: true

  value:
    description: Secret value
    required: true

  repository:
    description: Repository name
    default: ${{ github.repository }}
    required: false

  org:
    description: Indicate is an organization repo
    required: false

  token:
    description: Repository access token
    required: true

  visibility:
    description: For orgs only. Indicate access level all, private or selected
    required: false

  selected_repository_ids:
    description: Array of repository ids in case you set visibility as selected
    required: false

outputs:
  code:
    description: Status code

  data:
    description: Response data

runs:
  using: 'node12'
  main: 'dist/index.js'
  
  
