- name: Create Secrets File Action
  uses: du5rte/create-secrets-file@v1

uses: du5rte/create-secrets-file@v1
with:
  secrets: |
    API_KEY=${{ secrets.API_KEY }}
    SECRET_KEY=${{ secrets.SECRET_KEY }}
    DB_URI=${{ secrets.DB_URI }}
  # optionals
  # file: .env
  # mode: dotenv
  # path: src
  
  import 'secrets'
  
  module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['secrets/babel-plugin-secrets'],
}

Found ".env" in "/":
{
  API_KEY: ***
  SECRET_KEY: ***
  DB_URI: ***
}

API_KEY: 9j39j39j39j39j3
SECRET_KEY: 0k30k30k30k30k30k3
DB_URI: mongodb+srv://cluster-6f36f36f3.mongodb.net

