- name: OpenAPI Generator Action
  uses: kpurdon/openapi-generator-action@v0.0.3

- name: OpenAPI Generator Action
  uses: kpurdon/openapi-generator-action@[version]
  with:
      args: "generate -i spec.yaml -g typescript-fetch -o ./generated-code"
      
name: "OpenAPI Generator Action"
description: "Run the OpenAPI Generator CLI in a Github Action."
branding:
  icon: activity
  color: blue
runs:
  using: "docker"
  image: "docker://openapitools/openapi-generator-cli"
  
  
