name: autofix.ci  # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # TODO: add all code-fixing here.

      - uses: autofix-ci/action@8106fde54b877517c9af2c3d68918ddeaa7bed64
      
      name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Format your code with https://github.com/psf/black
      - uses: install-pinned/black@9f58745f83f0cc45dd3df3bb7cc6af5ebd41069a
      - run: black .

      # Sort imports with https://github.com/PyCQA/isort
      - uses: install-pinned/isort@3320ed76423156f6f847d2a7356dc668519b0cf2
      - run: isort .

      # Upgrade to the latest Python syntax with https://github.com/asottile/pyupgrade
      - uses: install-pinned/pyupgrade@0bb513444c8ff7ce06d3f76e271d1ee7028c3640
      - name: Run pyupgrade
        run: |  
          shopt -s globstar
          pyupgrade --exit-zero-even-if-changed --py310-plus **/*.py

      # Remove unused imports with https://github.com/PyCQA/autoflake
      - uses: install-pinned/autoflake@cb1e699963f33a074b04b3d197a0b27d46986c40
      - run: autoflake --in-place --remove-all-unused-imports -r .

      - uses: autofix-ci/action@8106fde54b877517c9af2c3d68918ddeaa7bed64
      
      name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm ci
      - run: npx prettier --write .

      - uses: autofix-ci/action@8106fde54b877517c9af2c3d68918ddeaa7bed64
      
      name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: cargo clippy --fix
      - run: cargo fmt

      - uses: autofix-ci/action@8106fde54b877517c9af2c3d68918ddeaa7bed64
      
      name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      # goimports works like gofmt, but also fixes imports.
      # see https://pkg.go.dev/golang.org/x/tools/cmd/goimports
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: goimports -w .
      # of course we can also do just this instead:
      # - run: gofmt -w .

      - uses: autofix-ci/action@8106fde54b877517c9af2c3d68918ddeaa7bed64
      
      name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Optimize all PNGs with https://pngquant.org/
      - run: sudo apt-get update && sudo apt-get install -y pngquant
      - run: |
          shopt -s globstar
          pngquant -f --ext .png --skip-if-larger -- **/*.png

      - uses: autofix-ci/action@8106fde54b877517c9af2c3d68918ddeaa7bed64
      
      name: autofix.ci
on:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: pip install pre-commit
      - run: pre-commit run --all-files

      - uses: autofix-ci/action@8106fde54b877517c9af2c3d68918ddeaa7bed64
      
      
