- name: Combine Pull Requests
  uses: bobvanderlinden/combine-pull-requests@v3

- uses: bobvanderlinden/combine-pull-requests@v3
  with:
    label: experiment
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    
name: My App CD
on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, labeled, unlabeled ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.label.name == 'experiment' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - uses: bobvanderlinden/combine-pull-requests@v3
        with:
          label: experiment
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: ansible-playbook deploy.yml
