CMD: "python mnist.py"

HPARAMS: [
  {
   RUNX.TAG: 'foo',
   lr: 0.01,
   momentum: [0.5, 0.25],
   logdir: LOGDIR,
  },
  {
   RUNX.TAG: 'bar',
   lr: 0.02,
   momentum: [0.25, 0.12],
   logdir: LOGDIR,
  },
]
   
