- name: Install the OpenAPITools Generator CLI
  uses: eak24/setup-openapi-generator-cli@v1

jobs:
  generate-angular-client:
    runs-on: ubuntu-latest
    name: Example
    steps:

      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v2

      # Generate your OpenAPI document (if you don't write it manually)

      # Use the action to generate a client package
      # This uses the default path for the openapi document and thus assumes there is an openapi.json in the current workspace.
      - name: Generate Angular Client
        uses: ethan92429/setup-openapi-generator-cli@v1
      - run: openapi-generator-cli -g typescript-angular -c angular-generator-config.yml

      # Do something with the generated client (likely publishing it somewhere)
      - name: Do something with the client
        run: |
          cd typescript-angular-client
          
 name: "Install the OpenAPITools Generator CLI"
description: "Installs the `openapi-generator-cli` to the command line to be used in subsequent steps."
branding:
  color: green

inputs:
  generator-tag:
    description: The Docker tag of the openapitools/openapi-generator-cli image to use.
    required: false
    default: latest

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo docker run -u 1001 --rm --workdir /github/workspace -v "${{ github.workspace }}:/github/workspace" openapitools/openapi-generator-cli:${{ inputs.generator-tag }} ${{ '\$@' }} > ${{ github.action_path }}/openapi-generator-cli
        chmod +x ${{ github.action_path }}/openapi-generator-cli
        echo ${{ github.action_path }} >> $GITHUB_PATH
        
        
