- name: PR Name Generator
  uses: devopsmakers/pr-name-generator-action@v0.0.4

name: 'PR Name Generator'
description: 'Generate a consistent, unique name based on PR'
branding:
  icon: 'anchor'
  color: 'blue'
outputs:
  name:
    description: 'The generated unique and consistent name'
runs:
  using: 'node16'
  main: 'dist/index.js'
  
  
