- name: Refresh Python Dependency
  uses: zehengl/refresh-python-dependency@v0.2.0

- uses: zehengl/refresh-python-dependency@main

- uses: zehengl/refresh-python-dependency@v0.2.0
  with:
    path: requirements-dev.txt
    
    - uses: zehengl/refresh-python-dependency@v0.2.0
  with:
    path: environment.yml
    
    - uses: zehengl/refresh-python-dependency@v0.2.0
  with:
    path: requirements1.txt
    extra_path: requirements2.txt
    
    name: pcu
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 12 * * 1"
jobs:
  refreshDeps:
    runs-on: ubuntu-latest
    steps:
      - uses: zehengl/refresh-python-dependency@v0.2.0
        with:
          path: requirements-dev.txt
          
          name: "Refresh Python Dependency"
description: "Refresh your dependency files in a Python repo"
inputs:
  path:
    description: "dependency file"
    required: false
    default: "requirements.txt"
  extra_path:
    description: "another dependency file"
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: Run pip-check-updates
      shell: bash
      run: |
        pip install pip-check-updates
        pcu ${{ inputs.path }} -u
        [[ -n "${{ inputs.extra_path }}" ]] && pcu ${{ inputs.extra_path }} -u || true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: refresh deps
        committer: GitHub <noreply@github.com>
        author: pcu-bot <pcu-bot@users.noreply.github.com>
        signoff: false
        branch: pcu-pr
        delete-branch: true
        title: "[pcu] Refresh Deps"
branding:
  icon: "box"
  color: "purple"
  
  
