- name: Dependabot Batcher
  uses: Legal-and-General/dependabot-batcher@v1.0.1

name: 'Dependabot Batcher: Scheduled'
on:
  schedule:
    - cron: '0 9 * * 1,3'

jobs:
  # Batches Dependabot PRs into one by merging them into a combined branch, then raising a new PR
  dependabot-batcher:
    name: 'Combine Dependabot PRs'
    uses: Legal-and-General/dependabot-batcher
    token: ${{ secrets.YOUR_TOKEN }} #required
    baseBranchName: 'master' #optional
    batchBranchName: 'dep-batcher-updates' #optional
    batchPullTitle: 'Dependabot Batcher Updates' #optional
    
    name: 'Pull Request'

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  someJob:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    
    🚫 These branches could not be combined:
dependabot/npm_and_yarn/nrwl/linter-14.5.1
dependabot/npm_and_yarn/nrwl/eslint-plugin-nx-14.5.1

name: Dependabot Batcher
description: An action to ease your dependency maintenance and save GitHub minutes.

inputs:
  token:
    description: A token with 'repo' and 'workflow' privileges
    required: true
  baseBranchName:
    description: The name of your default branch, usually 'main' or 'master'
    required: false
  batchBranchName:
    description: The name to give the branch containing your batched dependencies
    required: false
  batchPullTitle:
    description: The title to give the PR containing your batched dependencies
    required: false

branding:
  icon: 'box'
  color: 'blue'

runs:
  using: 'node16'
  main: 'dist/index.js'
  
  
