- name: Create dotenv from the secret file
  uses: taxidermic/ga-create-env@v1.2

name: "Create dotenv from the secret file"
description: "This action creates a .env file from a secret"
author: "taxidermic"
branding:
  icon: file-text
  color: green
inputs:
  filename:
    description: "The name of the file to be created"
    required: false
    default: ".env"
  secretname:
    description: "The secret from which to create a .env"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
  
  
