- name: @shqld / GitHub Script
  uses: shqld/github-script@v0.0.2

$ ls
.
└── .github
   ├── scripts
   │  └── hello.ts
   └── workflows
      └── ci.yaml     
      
jobs:
    steps:
        runs-on: ubuntu-latest
        steps:
            - uses: shqld/github-script@v1
              with:
                path: ./.github/scripts/hello.ts
       
import { Main } from '@shqld/github-script

export const main: Main = ({ github, context, core, ...args }) => {
    github.issues.createComment({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        body: 'Hello, world!',
    })
}
