- name: Pylint action
  uses: gabriel-milan/action-pylint@v1

on: pull_request

jobs:
  example:
    runs-on: ubuntu-latest
    name: Executes pylint
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        uses: gabriel-milan/action-pylint@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # GitHub token
          path: "./*.py" # Glob pattern for files to lint
          fail: true # Fail the action if pylint errors are found
          pr-message: true # Send a PR message if pylint errors are found
          
        name: "Pylint action"
description: "Runs pylint and sends errors in a PR message"
author: Gabriel Gazola Milan
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  path:
    description: "Path of files"
    required: true
  fail:
    description: "If true, the action will fail if pylint finds errors (default is true)"
    required: true
    default: true
  pr-message:
    description: "If true, the action will send a PR message if pylint finds errors (default is true)"
    required: true
    default: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "check"
  color: "green"
  
  
