- name: Python Pipenv Action
  uses: tiagovrtr/actions-pipenv@v1

name: CI
on: pull_request

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        pipenv-version: ["v2022.9.8", "v2022.9.21"]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pipenv"
      - name: Run image
        uses: tiagovrtr/actions-pipenv@v1
        with:
          pipenv-version: ${{ matrix.pipenv-version }}
      - name: View pipenv --help
        run: pipenv --help
        
        name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        pipenv-version: ["v2022.9.8", "v2022.9.21"]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: ./
        with:
          pipenv-version: ${{ matrix.pipenv-version }}
      - name: View pipenv --help
        run: pipenv --help
  release:
    if: github.event_name == 'push'
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      - name: Update major tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -d v1
          git push --delete origin v1
          git push origin :refs/tags/v1
          git tag v1
          git push --tags
          
         name: "Python Pipenv Action"
author: "@tiagovrtr"
description: "An action to run https://github.com/pypa/pipenv based on https://github.com/abatilo/actions-poetry"
branding:
  icon: "truck"
  color: "gray-dark"
inputs:
  pipenv-version:
    description: "The version of pipenv to install"
    required: true
    default: "2022.9.21"
runs:
  using: "composite"
  steps:
    - run: |
        pip install pipenv==${{ inputs.pipenv-version }}
      shell: bash
      
      
