- name: Check Python Version
  uses: samuelcolvin/check-python-version@v3


jobs:
  deploy:
    steps:
      - ...
      - uses: samuelcolvin/check-python-version@v3
        id: check-python-version
        with:
          version_file_path: mypackage/version.py

      - run: ...

      # optionally you can use the environment variables set by the action later
      - name: publish docs
        if: '!fromJSON(steps.check-python-version.outputs.IS_PRERELEASE)'
        uses: ...
        
        name: Check Python Version
author: Samuel Colvin <s@muelcolvin.com>
description: Check the release tag matches the library version before deploy

inputs:
  version_file_path:
    description: Path to python file containing the version number string
    required: true
  version_pattern:
    description: >
      Custom regular expression to find version with, defaults to
      `(?i)^(__version__|VERSION) *= *([\'"])v?(?P<version>.+?)\2`
    required: false
  test_github_ref:
    description: Version to check, defaults to using `GITHUB_REF` - this is mostly for testing
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: check-circle
  color: orange
  
  
