- name: Get Version from package.json
  uses: polyseam/get-version-from-package-json@1.0.0

on:
  pull_request:
    branches:
      - main
jobs:
  get-version-from-package-json-action:
    runs-on: ubuntu-latest
    name: Test get-version-from-package-json
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: get-version-from-package-json
        uses: polyseam/get-version-from-package-json@v.1.0.0
        id: get-version-from-package-json
        with:
          path-to-file: './test-data/package.json'
      - name: print-version
        run: echo "The version key in your json is ${{steps.get-version-from-package-json.outputs.version}}"
        
        
