- name: Update Updates Release Channel Expo.plist
  uses: Brune04/update-updates-release-channel-expo-plist-action@v1.3

- name: Update Expo.plist
  uses: Brune04/update-ios-version-info-plist-action@v1.3
  with:
      expo-plist-path: "./path_to_your/Expo.plist"
      updates-release-channel: "dev-2.0"
      print-file: true
      
      name: "Update Updates Release Channel Expo.plist"
description: "Update the Expo.plist file"
author: "Brune04"
inputs:
    expo-plist-path:
        description: "Relative path for the Expo.plist file."
        required: true
    updates-release-channel:
        description: "The Expo Updates Release Channel."
        required: true
    updates-runtime-version:
        description: "The Expo Updates Runtime Version."
        required: true
    print-file:
        description: "Output the Expo.plist file in console"
        required: false
runs:
    using: "node12"
    main: "dist/index.js"
branding:
    icon: "file"
    color: "blue"
    
    
